version: '3.1'

services:

  open_ai:
    image: open-ai-exp
    container_name: open-ai-exp
    ports:
       - 8090:8090
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:8090
      OPEN_AI_API_KEY: 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